apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: apps
spec:
  template:
    metadata:
      labels:
        app-type: default
    spec:
      nodeClassRef:
        name: ec2nodeclass-apps
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values:
            - m5.4xlarge
            - c5.4xlarge
            - r5.2xlarge
        - key: "karpenter.sh/capacity-type"
          operator: In
          values:
            - on-demand
        - key: "kubernetes.io/arch"
          operator: In
          values:
            - amd64
  limits:
    cpu: "32"
    memory: "128Gi"
  disruption:
    consolidateAfter: 30s
    expireAfter: null
