apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: apps
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        app-type: default
    spec:
      nodeClassRef:
        name: ec2nodeclass-apps
        kind: EC2NodeClass
        group: karpenter.k8s.aws

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.large"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

  limits:
    cpu: "200"
    memory: "400Gi"
